services:
  - type: web
    name: lab08-despliegue01
    runtime: node
    plan: free
    rootDir: despliegue01
    buildCommand: yarn install --frozen-lockfile
    startCommand: yarn start
    healthCheckPath: /
    autoDeployTrigger: commit

  - type: web
    name: lab08-portafolio-luis
    runtime: node
    plan: free
    rootDir: proyecto-anterior
    buildCommand: yarn install --frozen-lockfile
    startCommand: yarn start
    healthCheckPath: /
    autoDeployTrigger: commit
